# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: ganjimcin/cinblog # <--- ¡IMPORTANTE! Reemplaza esto con tu usuario y nombre de repositorio de GitHub.

media_folder: /static/media
public_folder: /media

collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Publication Date, name: pubDate, widget: datetime }
      - { label: Hero Image, name: heroImage, widget: image, required: false }
      - { label: Category, name: category, widget: select, options: [Cine, Tecnologia, Estilo de Vida, Noticias], default: Noticias }
      - { label: Body, name: body, widget: markdown }

  - name: pages
    label: Páginas
    folder: src/content/pages
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Body, name: body, widget: markdown }
