site:
  siteURL: https://eljardindeunapedagoga.vercel.app/
  title: El jardin de una pedagoga
  subtitle: Lili
  lang: es
  translate:
    enable: true
    service: client.edge
    showSelectTag: false
    autoDiscriminate: true
    ignoreClasses:
      - ignore
      - banner-title
      - banner-subtitle
    ignoreTags:
      - script
      - style
      - code
      - pre
  timeZone: 8
  font:
    Example - ZenMaruGothic:
      src: https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic&display=swap
      family: Zen Maru Gothic
  themeColor:
    hue: 255
  defaultTheme: dark
  wallpaper:
    mode: banner
    src:
      desktop:
        - /assets/images/desktopWallpaper_1.jpg
        - /assets/images/desktopWallpaper_2.jpg
        - /assets/images/desktopWallpaper_3.jpg
      mobile:
        - /assets/images/mobileWallpaper_1.jpg
        - /assets/images/mobileWallpaper_2.jpg
    position: center
    carousel:
      enable: true
      interval: 3.6
      kenBurns: true
    banner:
      homeText:
        enable: true
        title: El jardin de una pedagoga
        subtitle:
          - Life and Liberty
        typewriter:
          enable: true
          speed: 111
          deleteSpeed: 51
          pauseTime: 3000
      credit:
        enable: false
        text: Descripción
        url: ''
      navbar:
        transparentMode: semifull
      waves:
        enable: true
        performanceMode: false
    fullscreen:
      zIndex: -1
      opacity: 0.9
      blur: 1
      navbar:
        transparentMode: semi
  loadingOverlay:
    enable: true
    waitForAllResources: true
    title:
      enable: true
      content: CARGANDO
      interval: 1.5
    spinner:
      enable: true
      interval: 1.5
  favicon: []
  generateOgImages: false
navbar:
  links:
    - Home
    - Archive
    - About
sidebar:
  components:
    left:
      - type: profile
        position: top
        visibility:
          mode: exclude
          paths:
            - ^/posts/
            - ^/archive
      - type: directory
        position: sticky
      - type: categories
        position: sticky
        responsive:
          collapseThreshold: 5
        depth: 3
      - type: tags
        position: sticky
        responsive:
          collapseThreshold: 20
      - type: toc
        position: sticky
        depth: 3
    right: []
profile:
  avatar: /assets/images/avatar.jpg
  name: Lili Grow
  bio: Hola
  links:
    - name: GitHub
      icon: fa6-brands:github
      url: https://github.com/Spr-Aachen/Twilight
announcement:
  title: Anuncio
  content: ¡Bienvenido a mi blog!
  closable: true
  link:
    enable: true
    text: Saber más
    url: /about/
    external: false
post:
  showLastModified: true
  expressiveCode:
    theme: github-dark
  license:
    enable: true
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  comment:
    enable: false
footer:
  enable: false
particle:
  enable: true
  particleNum: 12
  limitTimes: -1
  size:
    min: 0.3
    max: 0.9
  opacity:
    min: 0.3
    max: 0.9
  speed:
    horizontal:
      min: -0.9
      max: 0.9
    vertical:
      min: 0.15
      max: 0.3
    rotation: 0.12
    fadeSpeed: 0.12
  zIndex: 100
musicPlayer:
  enable: true
  local:
    playlist:
      - id: 1
        title: Deep Sea Breath
        artist: Youzee Music
        cover: >-
          https://p1.music.126.net/PhKOqFtljgHDDpKYM2ADUA==/109951169858309716.jpg
        url: assets/music/深海之息.m4a
        lrc: assets/music/深海之息.lrc
        duration: 146
  autoplay: true
  fab:
    type: image
